#
# travis.yml
# Created by Felix Mau (https://felix.hamburg)
#
# Based on:
#  - http://www.mokacoding.com/blog/travis-ci-ios-testing/
#

osx_image: xcode10.2
language: swift
podfile: Example/Podfile
before_install:
- pod install --repo-update --project-directory=Example
script:
- ./Scripts/swift-format.sh
- ./Scripts/swift-lint.sh
- ./Scripts/test.sh
- ./Scripts/pod-lint.sh