#
# Travic CI configuration
#
# Based on:
#  - https://docs.travis-ci.com/user/languages/objective-c/#Default-Test-Script
#  - https://medium.com/@johnsundell/adding-continuous-integration-to-a-swift-project-4c99252eedb0
#

language: objective-c

osx_image: xcode8.3

script:
 - xcodebuild clean test -project GradientLoadingBar.xcodeproj -scheme GradientLoadingBar -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
