#
# travis.yml
# Created by Felix Mau (http://felix.hamburg)
#
# Based on:
#  - http://www.mokacoding.com/blog/travis-ci-ios-testing/
#

osx_image: xcode9.2
language: objective-c
podfile: Example/Podfile
before_install:
- brew install swiftlint
- pod install --project-directory=Example
script:
- ./Scripts/swift-lint.sh
- ./Scripts/test.sh
- ./Scripts/pod-lint.sh